page-object/config/routes.rb
Rails.application.routes.draw do
  resources :todos, only: [:index, :new, :create] do
    resource :completion, only: [:create, :destroy]
  end
end

page-object/app/models/todo.rb
class Todo < ActiveRecord::Base
  time_for_a_boolean :completed
end

page-object/app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :todos
end

page-object/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

page-object/app/controllers/completions_controller.rb
class CompletionsController < ApplicationController
  def create
    todos.find(params[:todo_id]).update_attribute :completed_at, Time.current
    redirect_to todos_path
  end

  def destroy
    todos.find(params[:todo_id]).update_attribute :completed_at, nil
    redirect_to todos_path
  end

  private

  def todos
    current_user.todos
  end
end

page-object/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = todos.all
  end

  def new
    @todo = todos.new
  end

  def create
    todos.create(todo_params)
    redirect_to todos_path
  end

  private

  def todo_params
    params.require(:todo).permit(:title)
  end

  def todos
    current_user.todos
  end
end

page-object/app/views/application/_analytics.html.erb
<% if ENV['SEGMENT_IO_KEY'] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.io/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load('<%= ENV['SEGMENT_IO_KEY'] %>');
    window.analytics.page();
  </script>
<% end %>

page-object/app/views/application/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end -%>
</div>

page-object/app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render 'analytics' %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

page-object/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, :media => 'all' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <%= render 'flashes' -%>

  <% if signed_in? %>
    Signed in as: <%= current_user.email %>
    <%= link_to 'Sign out', sign_out_path, :method => :delete %>
  <% else %>
    <%= link_to 'Sign in', sign_in_path %>
  <% end %>

  <%= yield %>

  <%= render 'javascript' %>
</body>
</html>

page-object/app/views/todos/index.html.erb
<%= link_to t('.create_todo'), new_todo_path %>

<% @todos.each do |todo| %>
  <div class="todo <%= "completed" if todo.completed? %>">
    <%= todo.title %>
    <% if todo.completed? %>
      <%= link_to t(".incomplete_todo"), todo_completion_path(todo), method: :delete %>
    <% else %>
      <%= link_to t(".complete_todo"), todo_completion_path(todo), method: :post %>
    <% end %>
  </div>
<% end %>

page-object/app/views/todos/new.html.erb
<%= simple_form_for @todo do |form| %>
  <%= form.input :title %>
  <%= form.submit %>
<% end %>